package com.ftg.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AddressGroup generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {

	private Integer id;
	private String postcode;
	private String address;
	private String isMail;
	private Date createDate;

	public Address() {
	}

	public Address(String address, Date createDate) {
		this.address = address;
		this.createDate = createDate;
	}

	public Address(String postcode, String address, String isMail, Date createDate) {
		this.postcode = postcode;
		this.address = address;
		this.isMail = isMail;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "postcode", length = 20)
	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "is_mail", length = 1)
	public String getIsMail() {
		return this.isMail;
	}

	public void setIsMail(String isMail) {
		this.isMail = isMail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
