package com.ftg.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers")
public class Customers implements java.io.Serializable {

	private Integer id;
	private String name;
	private String adNum;
	private String sex;
	private String custType;
	private int groupId;
	private String phone1;
	private String phone2;
	private int groupSort;
	private String lunarBirth;
	private String solarBirth;
	private String birthHour;
	private String lunarYear;
	private String zodiac;
	private String sevenStar;
	private String email;
	private String cardNum;
	private String notes;
	private String isActive;
	private Date createDate;
	private Integer createUserId;
	private Date updateDate;
	private Integer updateUserId;
	
	private int age;
	private String zhiHua;

	public Customers() {
	}

	public Customers(String name, String sex, String custType, int groupId, int groupSort, String lunarBirth,
			String solarBirth, String birthHour, String lunarYear, String zodiac, String sevenStar, String cardNum,
			String isActive) {
		this.name = name;
		this.sex = sex;
		this.custType = custType;
		this.groupId = groupId;
		this.groupSort = groupSort;
		this.lunarBirth = lunarBirth;
		this.solarBirth = solarBirth;
		this.birthHour = birthHour;
		this.lunarYear = lunarYear;
		this.zodiac = zodiac;
		this.sevenStar = sevenStar;
		this.cardNum = cardNum;
		this.isActive = isActive;
	}

	public Customers(String name, String adNum, String sex, String custType, int groupId, String phone1, String phone2, int groupSort,
			String lunarBirth, String solarBirth, String birthHour, String lunarYear, String zodiac, String sevenStar,
			String email, String cardNum, String notes, String isActive, Date createDate, Integer createUserId,
			Date updateDate, Integer updateUserId) {
		this.name = name;
		this.adNum = adNum;
		this.sex = sex;
		this.custType = custType;
		this.groupId = groupId;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.groupSort = groupSort;
		this.lunarBirth = lunarBirth;
		this.solarBirth = solarBirth;
		this.birthHour = birthHour;
		this.lunarYear = lunarYear;
		this.zodiac = zodiac;
		this.sevenStar = sevenStar;
		this.email = email;
		this.cardNum = cardNum;
		this.notes = notes;
		this.isActive = isActive;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.updateDate = updateDate;
		this.updateUserId = updateUserId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "ad_num", length = 10)
	public String getAdNum() {
		return adNum;
	}

	public void setAdNum(String adNum) {
		this.adNum = adNum;
	}

	@Column(name = "sex", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "cust_type", nullable = false, length = 10)
	public String getCustType() {
		return this.custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "phone1", nullable = false, length = 15)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "phone2", length = 15)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "group_sort", nullable = false)
	public int getGroupSort() {
		return this.groupSort;
	}

	public void setGroupSort(int groupSort) {
		this.groupSort = groupSort;
	}

	@Column(name = "lunar_birth", length = 10)
	public String getLunarBirth() {
		return this.lunarBirth;
	}

	public void setLunarBirth(String lunarBirth) {
		this.lunarBirth = lunarBirth;
	}

	@Column(name = "solar_birth", length = 10)
	public String getSolarBirth() {
		return this.solarBirth;
	}

	public void setSolarBirth(String solarBirth) {
		this.solarBirth = solarBirth;
	}

	@Column(name = "birth_hour", length = 2)
	public String getBirthHour() {
		return this.birthHour;
	}

	public void setBirthHour(String birthHour) {
		this.birthHour = birthHour;
	}

	@Column(name = "lunar_year", length = 2)
	public String getLunarYear() {
		return this.lunarYear;
	}

	public void setLunarYear(String lunarYear) {
		this.lunarYear = lunarYear;
	}

	@Column(name = "zodiac", length = 10)
	public String getZodiac() {
		return this.zodiac;
	}

	public void setZodiac(String zodiac) {
		this.zodiac = zodiac;
	}

	@Column(name = "seven_star", length = 10)
	public String getSevenStar() {
		return this.sevenStar;
	}

	public void setSevenStar(String sevenStar) {
		this.sevenStar = sevenStar;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "card_num", nullable = false, length = 32)
	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	@Column(name = "notes", length = 100)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user_id")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user_id")
	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	@Transient
	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Transient
	public String getZhiHua() {
		return zhiHua;
	}

	public void setZhiHua(String zhiHua) {
		this.zhiHua = zhiHua;
	}
}
