package com.ftg.dao.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdersPilgrimage generated by hbm2java
 */
@Entity
@Table(name = "orders_pilgrimage")
public class OrdersPilgrimage implements java.io.Serializable {

	private Integer id;
	private int ordersId;
	private int customersId;
	private String serialNo;
	private Integer amount;
	private String solarBirth;
	private String adNum;
	private String vegeFood;
	private String godName;

	public OrdersPilgrimage() {
	}

	public OrdersPilgrimage(int ordersId, int customersId, String serialNo, String solarBirth, String adNum) {
		this.ordersId = ordersId;
		this.customersId = customersId;
		this.serialNo = serialNo;
		this.solarBirth = solarBirth;
		this.adNum = adNum;
	}

	public OrdersPilgrimage(int ordersId, int customersId, String serialNo, String solarBirth, String adNum, Integer amount, 
			String vegeFood, String godName) {
		this.ordersId = ordersId;
		this.customersId = customersId;
		this.serialNo = serialNo;
		this.solarBirth = solarBirth;
		this.adNum = adNum;
		this.amount = amount;
		this.vegeFood = vegeFood;
		this.godName = godName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "orders_id", nullable = false)
	public int getOrdersId() {
		return this.ordersId;
	}

	public void setOrdersId(int ordersId) {
		this.ordersId = ordersId;
	}

	@Column(name = "customers_id", nullable = false)
	public int getCustomersId() {
		return this.customersId;
	}

	public void setCustomersId(int customersId) {
		this.customersId = customersId;
	}

	@Column(name = "serial_no", nullable = false, length = 20)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "vege_food", length = 1)
	public String getVegeFood() {
		return this.vegeFood;
	}

	public void setVegeFood(String vegeFood) {
		this.vegeFood = vegeFood;
	}

	@Column(name = "solar_birth", nullable = false, length = 10)
	public String getSolarBirth() {
		return solarBirth;
	}
	
	public void setSolarBirth(String solarBirth) {
		this.solarBirth = solarBirth;
	}

	@Column(name = "ad_num", nullable = false, length = 20)
	public String getAdNum() {
		return adNum;
	}
	
	public void setAdNum(String adNum) {
		this.adNum = adNum;
	}

	@Column(name = "god_name", length = 200)
	public String getGodName() {
		return godName;
	}

	public void setGodName(String godName) {
		this.godName = godName;
	}
}
