package com.ftg.dao.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdersDonateGold generated by hbm2java
 */
@Entity
@Table(name = "orders_donate_gold")
public class OrdersDonateGold implements java.io.Serializable {

	private Integer id;
	private int ordersId;
	private int customersId;
	private String serialNo;
	private Integer age;
	private Integer liang;
	private Integer chien;
	private Integer fen;
	private Integer li;

	public OrdersDonateGold() {
	}

	public OrdersDonateGold(int ordersId, int customersId, String serialNo) {
		this.ordersId = ordersId;
		this.customersId = customersId;
		this.serialNo = serialNo;
	}

	public OrdersDonateGold(int ordersId, int customersId, String serialNo, Integer age, Integer liang, Integer chien, Integer fen, Integer li) {
		this.ordersId = ordersId;
		this.customersId = customersId;
		this.serialNo = serialNo;
		this.age = age;
		this.liang = liang;
		this.chien = chien;
		this.fen = fen;
		this.li = li;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "orders_id", nullable = false)
	public int getOrdersId() {
		return this.ordersId;
	}

	public void setOrdersId(int ordersId) {
		this.ordersId = ordersId;
	}

	@Column(name = "customers_id", nullable = false)
	public int getCustomersId() {
		return this.customersId;
	}

	public void setCustomersId(int customersId) {
		this.customersId = customersId;
	}

	@Column(name = "serial_no", nullable = false, length = 20)
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "liang")
	public Integer getLiang() {
		return liang;
	}
	
	public void setLiang(Integer liang) {
		this.liang = liang;
	}

	@Column(name = "chien")
	public Integer getChien() {
		return chien;
	}

	public void setChien(Integer chien) {
		this.chien = chien;
	}

	@Column(name = "fen")
	public Integer getFen() {
		return fen;
	}

	public void setFen(Integer fen) {
		this.fen = fen;
	}

	@Column(name = "li")
	public Integer getLi() {
		return li;
	}
	
	public void setLi(Integer li) {
		this.li = li;
	}
}
