package com.ftg.dao.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProJieyuanPrice generated by hbm2java
 */
@Entity
@Table(name = "pro_jieyuan_price")
public class ProJieyuanPrice implements java.io.Serializable {

	private Integer id;
	private Integer jieyuanId;
	private String code;
	private String name;
	private int price;

	public ProJieyuanPrice() {
	}

	public ProJieyuanPrice(String code, String name, int price) {
		this.code = code;
		this.name = name;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "jieyuan_id", nullable = false)
	public Integer getJieyuanId() {
		return jieyuanId;
	}

	public void setJieyuanId(Integer jieyuanId) {
		this.jieyuanId = jieyuanId;
	}
	
	@Column(name = "code", nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

}
