package com.ftg.dao.entity;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ProStopResolve generated by hbm2java
 */
@Entity
@Table(name = "pro_stop_resolve")
public class ProStopResolve implements java.io.Serializable {

	private Integer id;
	private String sessions;
	private Integer groupInventory;
	private Integer groupQuantity;
	private Integer groupPrice;
	private String startRegDate;
	private String endRegDate;
	private Date createDate;
	private Integer createUserId;
	private Date updateDate;
	private Integer updateUserId;
	private String eventStart;
	private String eventEnd;
	
	private List<ProStopResolvePrice> stopResolvePrice;

	public ProStopResolve() {
	}

	public ProStopResolve(String sessions) {
		this.sessions = sessions;
	}

	public ProStopResolve(String sessions, Integer groupInventory, Integer groupQuantity, Integer groupPrice, String startRegDate, String endRegDate,
			Date createDate, Integer createUserId, Date updateDate, Integer updateUserId, String eventStart, String eventEnd) {
		this.sessions = sessions;
		this.groupInventory = groupInventory;
		this.groupQuantity = groupQuantity;
		this.groupPrice = groupPrice;
		this.startRegDate = startRegDate;
		this.endRegDate = endRegDate;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.updateDate = updateDate;
		this.updateUserId = updateUserId;
		this.eventStart = eventStart;
		this.eventEnd = eventEnd;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sessions", nullable = false, length = 20)
	public String getSessions() {
		return this.sessions;
	}

	public void setSessions(String sessions) {
		this.sessions = sessions;
	}

	@Column(name = "group_inventory")
	public Integer getGroupInventory() {
		return groupInventory;
	}

	public void setGroupInventory(Integer groupInventory) {
		this.groupInventory = groupInventory;
	}
	
	@Column(name = "group_quantity")
	public Integer getGroupQuantity() {
		return groupQuantity;
	}

	public void setGroupQuantity(Integer groupQuantity) {
		this.groupQuantity = groupQuantity;
	}

	@Column(name = "group_price")
	public Integer getGroupPrice() {
		return this.groupPrice;
	}
	
	public void setGroupPrice(Integer groupPrice) {
		this.groupPrice = groupPrice;
	}

	@Column(name = "start_reg_date", length = 10)
	public String getStartRegDate() {
		return this.startRegDate;
	}

	public void setStartRegDate(String startRegDate) {
		this.startRegDate = startRegDate;
	}

	@Column(name = "end_reg_date", length = 10)
	public String getEndRegDate() {
		return this.endRegDate;
	}

	public void setEndRegDate(String endRegDate) {
		this.endRegDate = endRegDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user_id")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user_id")
	public Integer getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}
	
	@Column(name = "event_start", length = 10)
	public String getEventStart() {
		return eventStart;
	}
	
	public void setEventStart(String eventStart) {
		this.eventStart = eventStart;
	}

	@Column(name = "event_end", length = 10)
	public String getEventEnd() {
		return eventEnd;
	}

	public void setEventEnd(String eventEnd) {
		this.eventEnd = eventEnd;
	}

	@Transient
	public List<ProStopResolvePrice> getStopResolvePrice() {
		return stopResolvePrice;
	}

	public void setStopResolvePrice(List<ProStopResolvePrice> stopResolvePrice) {
		this.stopResolvePrice = stopResolvePrice;
	}
}
